<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_John  Doe</name>
   <tag></tag>
   <elementGuidId>3995ba33-57d2-4372-b29d-1b3a9131efa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/tbody/tr[2]/td[3]/a//preceding::input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.left > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dbb7eb0-c74b-4ebb-8ce3-a6bd7f09b1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>addCandidate?id=23</value>
      <webElementGuid>e15a1477-1bdc-408d-9cc2-7203c445a21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>John  Doe</value>
      <webElementGuid>0f034f80-5f23-4a22-abe7-218c86529f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;left&quot;]/a[1]</value>
      <webElementGuid>d6ee2e41-5c29-415b-abed-e45d4c599ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>962a61cc-bdb8-431e-a4c1-308a7fc06006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'John  Doe')]</value>
      <webElementGuid>34fcf66e-b060-4177-8d77-60180fbcc8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume'])[1]/following::a[3]</value>
      <webElementGuid>afef2c34-ef00-45b2-b2e1-ec50c4203600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associate IT Manager'])[2]/preceding::a[4]</value>
      <webElementGuid>3225bb4a-12df-4569-89c2-7e6e69d9d71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'addCandidate?id=23')]</value>
      <webElementGuid>ee1cac9a-cbf2-4014-af8e-a1185e7cb451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a</value>
      <webElementGuid>925c72a9-f625-43f9-824a-63fcc17a8cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'addCandidate?id=23' and (text() = 'John  Doe' or . = 'John  Doe')]</value>
      <webElementGuid>535de46d-bb84-424e-a55d-3737d200af6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
