<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>76763f02-6eb6-4fbb-8ea1-b88ed13e98aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_core_viewDefinedPredefinedReports</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffe840c1-de6f-4989-9a51-d1c6de3d9273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED</value>
      <webElementGuid>f83669ec-29e5-4511-84e0-febc12702533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_core_viewDefinedPredefinedReports</value>
      <webElementGuid>50801407-4d8e-4d3a-89dd-4a5e462bacfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>963eea35-1781-429d-b092-a2b93582ca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_core_viewDefinedPredefinedReports&quot;)</value>
      <webElementGuid>b0dda75d-314c-43bd-8562-e7b031139929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      <webElementGuid>eb4c4852-4eb5-42c4-835f-f9627b5b61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[2]/ul/li[4]/a</value>
      <webElementGuid>b40d643b-e9f3-4002-b0b3-2ba29c2c7f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reports')]</value>
      <webElementGuid>bdb004da-c754-4984-ba43-db258c146ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Employee'])[1]/following::a[1]</value>
      <webElementGuid>572afc52-afad-49e2-aed4-14883f8e85df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/following::a[2]</value>
      <webElementGuid>c0d81552-313b-4edb-80de-bb498c7401fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>a6639807-7e50-459c-932c-961f6c4c40f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::a[2]</value>
      <webElementGuid>790af1c9-30f4-40ea-a96f-a785171ef6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reports']/parent::*</value>
      <webElementGuid>12efd7e5-1ca5-4eb0-97f4-a64c07a2332c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED')]</value>
      <webElementGuid>6a71784f-5f9b-4652-b1a0-a52a2da9298f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>dcfccac0-cfe7-42c4-bad3-1a83bc1e76a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED' and @id = 'menu_core_viewDefinedPredefinedReports' and (text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>156fa995-4f53-4d36-87b1-e60bc1661cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
