<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tax ID_organizationtaxId</name>
   <tag></tag>
   <elementGuidId>874448a4-9687-4cbd-95b6-052de9f0065c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_taxId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#organization_taxId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbbd9a31-a85d-4e14-9d19-34d20eb2068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd988818-ed1f-44b2-8c4b-ee58df06ea08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization[taxId]</value>
      <webElementGuid>d177ec6c-cf42-480b-b9c1-d29030faf08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>883f5866-3afb-40e2-8821-6995b52f8ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_taxId</value>
      <webElementGuid>34f843c0-b870-47f7-b9dd-01631b945d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_taxId&quot;)</value>
      <webElementGuid>d1dd57fc-b335-45ad-9c49-01e1c3d849ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_taxId']</value>
      <webElementGuid>6aa5d2ca-e430-4596-b6e5-cdc337b7f910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol/li[2]/input</value>
      <webElementGuid>c882dfc7-7245-40ba-b6da-ad6a06acdea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>0f7dfd18-d7e5-4ece-a2ed-bbaab9e8bb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization[taxId]' and @id = 'organization_taxId']</value>
      <webElementGuid>8b30095f-0ee3-49e8-b12a-c3932f4ac0d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
