<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report Name_btnAdd</name>
   <tag></tag>
   <elementGuidId>51d2b631-5c42-4b2d-ae08-29ef44d60f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb79ca08-e730-4d08-bf32-7d72d0901d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcb25e74-5f19-43dc-b1dc-2d96e79b833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>02b328fc-63f4-47fe-9d42-c38182edc8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAdd</value>
      <webElementGuid>5863f2bd-6b0f-4aaa-9d31-5e6824e9b7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAdd</value>
      <webElementGuid>b674d264-9b63-48f8-9591-420e8c068eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>4906f1d2-d4bf-43d6-a024-698063167bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAdd&quot;)</value>
      <webElementGuid>3eeb298a-d42c-42fb-acc3-20f656352ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAdd']</value>
      <webElementGuid>a7b77113-b210-4c53-9f32-99462291a18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input</value>
      <webElementGuid>e036ff15-8570-41d2-82c0-0982618d838a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>eb9b0be9-cc80-468e-9584-733e27ea8d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnAdd' and @name = 'btnAdd']</value>
      <webElementGuid>f7623420-7a1a-4849-8cf6-49afc36ae009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
