<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reportreport_name (1)</name>
   <tag></tag>
   <elementGuidId>9db5f87a-3e93-4b24-b98c-eec46cea1a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_report_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='report_report_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a413cac9-a81f-44f1-8865-81b05ab855d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8dd7de8-72e0-481c-8efa-defe04f7c54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>report[report_name]</value>
      <webElementGuid>7d172ba0-fde6-4a32-8673-08403a612bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_report_name</value>
      <webElementGuid>6f9016dd-1543-4658-9149-1de3d3d6055a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_report_name&quot;)</value>
      <webElementGuid>de69a4f9-3393-4e35-903b-97131912829b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='report_report_name']</value>
      <webElementGuid>43692b4e-3a81-4339-ad51-519338ad02c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='name_fieldset']/ol/li/input</value>
      <webElementGuid>7b213940-19df-42bc-99ae-24f81728e461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>01e7c53e-f56a-4d62-87a4-807936b5682d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'report[report_name]' and @id = 'report_report_name']</value>
      <webElementGuid>979be228-5670-481d-8fe2-79ae056cc303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
