<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_httpsopensource-demo.orangehrmlive.co_0ab0d0</name>
   <tag></tag>
   <elementGuidId>e117dd23-6f1b-41fc-bc9f-fea54c425778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnBack']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnBack</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>520ffbca-bff1-43d7-8ab3-37bec8067af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59b91a86-9b49-411d-8c20-5457afcde43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel hover</value>
      <webElementGuid>e841e34c-049a-44d5-81b4-5e5b3feca532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnBack</value>
      <webElementGuid>7f4c287e-8f4c-4b42-a520-337dc20357d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnBack</value>
      <webElementGuid>a431ef80-88d9-4484-b831-4ef7e99b57fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>3b2eb5f1-a9e6-476b-ac13-f2c6d0ccc67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnBack&quot;)</value>
      <webElementGuid>7bd1d916-55ed-4c7c-9e5e-15e8764c9916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnBack']</value>
      <webElementGuid>4ec5406a-e38c-4907-a675-cf8302e1280f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddJobVacancy']/fieldset/p/input[2]</value>
      <webElementGuid>5376918b-6005-495d-bb0c-a0f193281536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input[2]</value>
      <webElementGuid>b9b70e81-0616-4d58-853b-b777a242e3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnBack' and @id = 'btnBack']</value>
      <webElementGuid>d8380e15-77d6-48d2-abfc-9d28684dc046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
