<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Skills (Include Header)_display_groups</name>
   <tag></tag>
   <elementGuidId>d695a738-1bb3-4fda-bb7f-ce3728b1db18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#display_group_12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='display_group_12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>154bfcad-3ba5-46df-83fe-485824057afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_group_12</value>
      <webElementGuid>93fb623e-0945-476a-b889-b149072c29f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>display_groups[]</value>
      <webElementGuid>e66284bf-e19f-48cf-9e50-79aa67e8d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>08f73ab5-1992-403c-b571-fd859ee74870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>3d419540-81dd-4ff7-9280-9c2ff5a263cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_group_12&quot;)</value>
      <webElementGuid>e6030e8d-1a44-4a21-a894-3434ce5ebd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='display_group_12']</value>
      <webElementGuid>b42e2e42-493d-4e32-ba4d-901b204e7e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='display_groups']/li[9]/input</value>
      <webElementGuid>c07864f5-091a-443f-b682-d0c2bd800e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/input</value>
      <webElementGuid>ba99e3b1-e199-4ebc-bbbc-732bba1bc3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'display_group_12' and @name = 'display_groups[]' and @type = 'checkbox']</value>
      <webElementGuid>92d26683-f9af-4b2c-b1f1-61a13883586d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
