<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resume_addCandidateresume</name>
   <tag></tag>
   <elementGuidId>6405ff6a-bd37-408c-bf5e-66ea2a2ac3da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addCandidate_resume']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addCandidate_resume</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5e4aaf8-541b-44bd-9663-98296e9b61a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cba9b7e2-3840-4a3c-bffc-d74b9f6acb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addCandidate[resume]</value>
      <webElementGuid>6da1ab45-8e74-47fa-b633-b2e148355737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addCandidate_resume</value>
      <webElementGuid>d6c37c80-b36a-4f93-8550-00bf8a957fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCandidate_resume&quot;)</value>
      <webElementGuid>cd211e9c-f379-46cc-9406-fa716bad0746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addCandidate_resume']</value>
      <webElementGuid>ecfd20bb-d9e4-42ab-97c0-385f0323eace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddCandidate']/fieldset/ol[2]/li[2]/input</value>
      <webElementGuid>823f53f2-c853-49eb-9755-6391fa1350dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li[2]/input</value>
      <webElementGuid>7da1e66d-7c1e-4c65-8434-f42a22b1c1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'addCandidate[resume]' and @id = 'addCandidate_resume']</value>
      <webElementGuid>c8d818a6-16fa-43d5-a61c-fbf9146096b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
