<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal (Include Header)_display_groups</name>
   <tag></tag>
   <elementGuidId>cfdf5152-03b2-4b33-8e60-43ba3ef52741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#display_group_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='display_group_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd41025-fed0-4844-873a-9ea4f5531414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_group_1</value>
      <webElementGuid>63317858-a23c-4587-87ce-be00873e0ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>display_groups[]</value>
      <webElementGuid>6a0716d2-439f-4676-a191-cc44b3b66604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0bfc6f97-7a29-4c26-a0cf-49201f580a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbdbf05d-9079-48bf-8fa3-74aed3a1b8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_group_1&quot;)</value>
      <webElementGuid>3d08cd46-9ac5-4a90-9fa6-e5f6cb2e76cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='display_group_1']</value>
      <webElementGuid>35a914cf-4eb7-47dc-958e-29e3cf091318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='display_groups']/li[2]/input</value>
      <webElementGuid>c3e435d4-78fe-4eac-9b46-29a5760387e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>8257b0ed-a866-48db-903c-a44be17987d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'display_group_1' and @name = 'display_groups[]' and @type = 'checkbox']</value>
      <webElementGuid>9e4ad400-502c-4d23-968d-fd82c21f21f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
