<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reportreport_name</name>
   <tag></tag>
   <elementGuidId>780f0402-97cf-4325-bec6-463482e94ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_report_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='report_report_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa3c0808-9225-4497-83f7-e2f1c21a3548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b991828-c8c6-48be-8917-36524f72cf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>report[report_name]</value>
      <webElementGuid>29bddbce-c389-4880-8ca0-03ba03acc866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_report_name</value>
      <webElementGuid>f0a7322f-53d8-4bf6-bc33-488d73bbe1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_report_name&quot;)</value>
      <webElementGuid>00195408-008f-4e01-b525-88308060d024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='report_report_name']</value>
      <webElementGuid>88187376-bc73-4eb3-a206-5beee7c2427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='name_fieldset']/ol/li/input</value>
      <webElementGuid>f3363b2c-95c5-4f4d-a59a-38a3557a44ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>1e99b914-3996-4d44-8ff3-4e51cb4b24d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'report[report_name]' and @id = 'report_report_name']</value>
      <webElementGuid>92fe74b8-05bf-45af-8c89-494ba3110880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
