<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_organizationphone</name>
   <tag></tag>
   <elementGuidId>3f0d99e2-f54a-441c-99d9-0413360ef45d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#organization_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a84554a-0a78-447c-bdac-5b183b33864f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3da10c35-c058-4150-9aed-450dbfce96e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization[phone]</value>
      <webElementGuid>64328e89-c9cb-40b0-bbff-4988e02c09bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4406c725-7999-4566-b9cc-2c5a3a92c319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_phone</value>
      <webElementGuid>d39643fe-cc47-4398-a5cc-ce8710fc9e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_phone&quot;)</value>
      <webElementGuid>87899a7b-dee1-4d6a-a5be-db4662743b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_phone']</value>
      <webElementGuid>a9d28c01-e0ca-4d62-9521-abd38ad77625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol[2]/li/input</value>
      <webElementGuid>b41da98c-8c7c-42e9-8650-39a063cdb45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li/input</value>
      <webElementGuid>432ba846-f0db-4eff-a08b-452c8493ddc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization[phone]' and @id = 'organization_phone']</value>
      <webElementGuid>73618b5c-bcf1-406d-b7e1-9d2644df616f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
