<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Street 1_organizationstreet1</name>
   <tag></tag>
   <elementGuidId>2e816f77-1794-43bc-8fab-656d379aa1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_street1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#organization_street1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66ad79ef-2bbe-4f2e-adb7-3eb5dcdeffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdaf7571-efdf-4da9-88bd-2ab025521733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization[street1]</value>
      <webElementGuid>3b174ed1-7513-4cd6-ae94-ef021bad9262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>538 Teal Plaza</value>
      <webElementGuid>a71fc91f-b880-4d56-9b63-a4c5473e3fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>58c9db7d-37fa-442a-8b89-0e6431d0b3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_street1</value>
      <webElementGuid>91dfbe05-efcb-4745-a123-876ce1a7026b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_street1&quot;)</value>
      <webElementGuid>bf7c8b21-a0a2-4db2-8d70-c850cacd7476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_street1']</value>
      <webElementGuid>3b46b5d7-64af-49c3-b089-2d0c5f8d8917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol[3]/li/input</value>
      <webElementGuid>421f4474-2675-498f-bd68-2cbf10dbd0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li/input</value>
      <webElementGuid>6838feb7-b532-4cd3-b9ad-b957aa7e79cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization[street1]' and @id = 'organization_street1']</value>
      <webElementGuid>e08b87f4-22c1-496c-9a85-4b5ed96666fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
