<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Allows numbers and only  -  ( )</name>
   <tag></tag>
   <elementGuidId>3444aa9c-8b65-485d-b881-a95469ae1c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmGenInfo']/fieldset/ol[2]/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>067baa5b-bc3f-4b41-8e46-5e49a1394063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>organization_phone</value>
      <webElementGuid>c81473b1-c0c7-4187-82c7-07524538dfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>630f2401-2ecf-49ac-bd23-5ad0b33f8877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>46e6bb13-7990-4f24-b8f5-a71b9dd57579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allows numbers and only + - / ( )</value>
      <webElementGuid>c9328d88-550a-43d4-9cac-b8945c5bd815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmGenInfo&quot;)/fieldset[1]/ol[2]/li[1]/span[@class=&quot;validation-error&quot;]</value>
      <webElementGuid>df00a752-a7ae-487c-b8a8-a388bc58765a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol[2]/li/span</value>
      <webElementGuid>00d78d9c-533a-4e3a-81e6-312d0d13694b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::span[1]</value>
      <webElementGuid>6489bab0-941f-497e-bca4-3a236c4e312f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Number'])[1]/following::span[1]</value>
      <webElementGuid>ef1cbeb2-5e5e-4299-852b-bb8f8008236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax'])[1]/preceding::span[1]</value>
      <webElementGuid>f5a9de28-8700-41c3-a18c-ef8b9af72199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::span[1]</value>
      <webElementGuid>f2fed851-5c86-412a-b591-2df6b5fcaf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allows numbers and only + - / ( )']/parent::*</value>
      <webElementGuid>b1d0712a-5694-41b9-8688-966fc5e7b008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li/span</value>
      <webElementGuid>e2d2b2d5-08c3-4c35-96d3-4207aa131b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Allows numbers and only + - / ( )' or . = 'Allows numbers and only + - / ( )')]</value>
      <webElementGuid>3100554f-d219-43dc-8a24-0edb1f8bb09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
